package uk.gov.justice.digital.hmpps.prisonerpropertyapi.dto

import io.swagger.v3.oas.annotations.media.Schema
import uk.gov.justice.digital.hmpps.prisonerpropertyapi.domain.ContainerStatus
import uk.gov.justice.digital.hmpps.prisonerpropertyapi.domain.ContainerType
import uk.gov.justice.digital.hmpps.prisonerpropertyapi.domain.PropertyContainer
import uk.gov.justice.digital.hmpps.prisonerpropertyapi.domain.PropertyEvent
import uk.gov.justice.digital.hmpps.prisonerpropertyapi.domain.PropertyEventType
import uk.gov.justice.digital.hmpps.prisonerpropertyapi.domain.StorageLocationType
import java.time.LocalDate
import java.time.LocalDateTime
import java.util.UUID

/**
 * Whether a timeline item is something that happened to a single container, a prisoner movement between prisons,
 * or a forward-looking "scheduled for release" marker synthesised from the prisoner's release dates.
 */
enum class TimelineItemType {
  CONTAINER_EVENT,
  PRISONER_MOVEMENT,
  SCHEDULED_FOR_RELEASE,
}

/** For a prisoner-movement item, whether it was an initial admission into custody or a transfer in from another prison. */
enum class MovementKind {
  ADMISSION,
  TRANSFER_IN,
}

/**
 * A single item in a prisoner's whole-property history timeline: either an event against one of their
 * containers, or a prisoner movement ("arrived at ...") derived from the received events. All prison and
 * location ids are resolved to names so the item can be rendered without further lookups. Seal numbers and
 * the acting establishment are the values *as at that point in the container's history*, so the timeline
 * reads correctly even after later seal changes or transfers.
 */
@Schema(description = "A single item in a prisoner's whole-property history timeline")
data class PrisonerTimelineItemDto(
  @Schema(description = "Whether the item is a container event or a prisoner movement", example = "CONTAINER_EVENT")
  val itemType: TimelineItemType,

  @Schema(description = "For a prisoner movement, whether it was an initial admission or a transfer in; null otherwise", example = "ADMISSION", nullable = true)
  val movementKind: MovementKind?,

  @Schema(description = "Id of the underlying event", example = "0196f1d3-9a1f-7c3a-9b2e-2c1f3a4b5c6d")
  val eventId: UUID,

  @Schema(description = "What happened to the container, for container events; null for prisoner movements", example = "TRANSFERRED", nullable = true)
  val eventType: PropertyEventType?,

  @Schema(description = "The status this event put the container into (used for the item's status tag); null for prisoner movements", example = "TRANSFER", nullable = true)
  val eventStatus: ContainerStatus?,

  @Schema(description = "When the event happened")
  val eventDateTime: LocalDateTime,

  @Schema(description = "Business date the event relates to (e.g. proposed disposal date), if any", example = "2026-09-15", nullable = true)
  val eventDate: LocalDate?,

  @Schema(description = "Id of the user who recorded the event", example = "AUSER_GEN")
  val eventUserId: String,

  @Schema(description = "Whether the event was generated by the system rather than a user", example = "false")
  val systemGenerated: Boolean,

  @Schema(description = "Name of the prisoner, for prisoner movement items; null for container events", example = "Matthew Sonom", nullable = true)
  val prisonerName: String?,

  @Schema(description = "Name of the establishment that performed the action (for the byline); the destination prison for a movement", example = "Leeds (HMP)", nullable = true)
  val actingEstablishmentName: String?,

  @Schema(description = "Name of the prison the container moved from, for transfer/disposal/return events", example = "Leeds (HMP)", nullable = true)
  val fromPrisonName: String?,

  @Schema(description = "Name of the prison the container moved to, for transfer/received events (and the arrival prison for a movement)", example = "Isle of Wight (HMP)", nullable = true)
  val toPrisonName: String?,

  @Schema(description = "Storage location type the container moved to (INTERNAL or offsite BRANSTON), for move events", example = "BRANSTON", nullable = true)
  val toStorageLocationType: StorageLocationType?,

  @Schema(description = "The container's seal number as at the time of this event", example = "SN880032", nullable = true)
  val sealNumber: String?,

  @Schema(description = "Id of a related container, for combine events", example = "33333333-3333-3333-3333-333333333333", nullable = true)
  val relatedContainerId: UUID?,

  @Schema(description = "Id of the container this event belongs to; null for prisoner movements", example = "0196f1d3-9a1f-7c3a-9b2e-2c1f3a4b5c6d", nullable = true)
  val containerId: UUID?,

  @Schema(description = "Type of the container, for the item's expandable details; null for prisoner movements", example = "STANDARD", nullable = true)
  val containerType: ContainerType?,

  @Schema(description = "The container's current seal number, for the item's expandable details", example = "SN880032", nullable = true)
  val containerSealNumber: String?,

  @Schema(description = "The container's current status, for the item's expandable details", example = "STORED", nullable = true)
  val containerStatus: ContainerStatus?,

  @Schema(description = "Human-friendly description of the container's current location, for the item's expandable details", example = "Reception Property Store", nullable = true)
  val containerLocationDescription: String?,
) {
  companion object {
    /** Any event recorded by the system rather than a user carries this reserved user id. */
    private const val SYSTEM_USER = "PRISONER_PROPERTY_API"

    /** Build a container-event item, given the seal-as-at-this-event and the resolved prison/location names. */
    fun containerEvent(
      event: PropertyEvent,
      container: PropertyContainer,
      sealAsOfEvent: String?,
      actingEstablishmentName: String?,
      fromPrisonName: String?,
      toPrisonName: String?,
      containerLocationDescription: String?,
    ) = PrisonerTimelineItemDto(
      itemType = TimelineItemType.CONTAINER_EVENT,
      movementKind = null,
      eventId = event.id!!,
      eventType = event.eventType,
      eventStatus = event.eventType.status,
      eventDateTime = event.eventDateTime,
      eventDate = event.eventDate,
      eventUserId = event.eventUserId,
      systemGenerated = event.eventUserId == SYSTEM_USER,
      prisonerName = null,
      actingEstablishmentName = actingEstablishmentName,
      fromPrisonName = fromPrisonName,
      toPrisonName = toPrisonName,
      toStorageLocationType = event.toStorageLocationType,
      sealNumber = sealAsOfEvent,
      relatedContainerId = event.relatedContainerId,
      containerId = container.id,
      containerType = container.containerType,
      containerSealNumber = container.currentSealNumber,
      containerStatus = container.currentStatus(),
      containerLocationDescription = containerLocationDescription,
    )

    /**
     * Build a synthesised prisoner-movement item (an admission into custody or a transfer in from another
     * prison), derived at read time from prison-api. Not backed by a stored event, so it carries a
     * deterministic id derived from the prisoner, kind, destination prison and date, and sits on the timeline
     * at the date the person entered that prison.
     */
    fun prisonerMovement(
      kind: MovementKind,
      prisonerNumber: String,
      prisonerName: String?,
      dateInToPrison: LocalDateTime,
      toPrisonId: String,
      toPrisonName: String?,
    ) = PrisonerTimelineItemDto(
      itemType = TimelineItemType.PRISONER_MOVEMENT,
      movementKind = kind,
      eventId = UUID.nameUUIDFromBytes("movement:$prisonerNumber:$kind:$toPrisonId:$dateInToPrison".toByteArray()),
      eventType = null,
      eventStatus = null,
      eventDateTime = dateInToPrison,
      eventDate = null,
      eventUserId = SYSTEM_USER,
      systemGenerated = true,
      prisonerName = prisonerName,
      actingEstablishmentName = toPrisonName,
      fromPrisonName = null,
      toPrisonName = toPrisonName,
      toStorageLocationType = null,
      sealNumber = null,
      relatedContainerId = null,
      containerId = null,
      containerType = null,
      containerSealNumber = null,
      containerStatus = null,
      containerLocationDescription = null,
    )

    /**
     * Build a synthesised "scheduled for release" marker for the prisoner. It is not backed by a stored event,
     * so it carries a deterministic id derived from the prisoner number and date, and sits on the timeline at the
     * release date (start of day) so an upcoming release surfaces at the top of the newest-first list.
     */
    fun scheduledForRelease(
      prisonerNumber: String,
      prisonerName: String?,
      releaseDate: LocalDate,
    ) = PrisonerTimelineItemDto(
      itemType = TimelineItemType.SCHEDULED_FOR_RELEASE,
      movementKind = null,
      eventId = UUID.nameUUIDFromBytes("scheduled-release:$prisonerNumber:$releaseDate".toByteArray()),
      eventType = null,
      eventStatus = null,
      eventDateTime = releaseDate.atStartOfDay(),
      eventDate = releaseDate,
      eventUserId = SYSTEM_USER,
      systemGenerated = true,
      prisonerName = prisonerName,
      actingEstablishmentName = null,
      fromPrisonName = null,
      toPrisonName = null,
      toStorageLocationType = null,
      sealNumber = null,
      relatedContainerId = null,
      containerId = null,
      containerType = null,
      containerSealNumber = null,
      containerStatus = null,
      containerLocationDescription = null,
    )
  }
}
